# WRLinux additional openssl-fips configuration path
EXTRA_KERNEL_FILES =. "${LAYER_PATH_wrlinux}/templates/feature/openssl-fips/files:"
EXTRA_KERNEL_SRC_URI += "file://crypto-fips.cfg"

PACKAGECONFIG:append:pn-openssl = " fips"
