# Tell RPM to enforce signature verification on the target
PACKAGECONFIG:append:pn-rpm = " sequoia keyringpath"
PACKAGECONFIG:append:pn-rpm-native = " sequoia"

# Tell dnf to enforce signature verification on the target
PACKAGECONFIG:append:pn-dnf = " keyringpath"
