FROM elxrlinux/elxr:12.10.0.0

RUN \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confnew" -qy install --no-install-recommends \
    #Part 1: packages recommended by yocto doc
    build-essential \
    chrpath \
    cpio \
    debianutils \
    diffstat \
    file \
    gawk \
    gcc \
    git \
    iputils-ping \
    libacl1 \
    liblz4-tool \
    locales \
    python3 \
    python3-git \
    python3-jinja2 \
    python3-pexpect \
    python3-pip \
    python3-subunit \
    socat \
    texinfo \
    tini \
    unzip \
    wget \
    xz-utils \
    zstd \
    # Part 2: packages added since other reasons
    bash \
    bzip2 \
    curl \
    help2man \
    iproute2 \
    openssh-client \
    patch \
    screen \
    strace \
    subversion \
    sudo \
    sysstat \
    texi2html \ 
    time \
    vim \
    vim-bitbake && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /usr/share/man && \
    rm -rf /usr/share/doc && \
    rm -rf /usr/share/grub2 && \
    rm -rf /usr/share/texmf/fonts && \
    rm -rf /usr/share/texmf/doc && \
    echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen && \
    locale-gen && \
    update-locale LANG=en_US.UTF-8

# add user to sudoers after sudo is installed
RUN useradd -m --uid 1000 --gid 100 --shell /bin/bash wrlbuild && \
    echo "wrlbuild ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

ENTRYPOINT ["/bin/tini", "-g"]

CMD ["/bin/bash"]

USER wrlbuild
