# Enable building OpenVINO Python API.
PACKAGECONFIG:append:pn-openvino-inference-engine = " python3"
# Enable Intel GPU plugin compilation.
PACKAGECONFIG:append:x86-64:pn-openvino-inference-engine = " opencl"
